name: Deploy site
on:
  push:
   branches:
   - deploy

jobs:
  deploy-site:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone site
      run: bash clone-site.sh

    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: ./partytown.pythonanywhere.com
        force_orphan: true
    - name: "Print Run ID"
      run: echo $GITHUB_RUN_ID
